---
title: "Draft Recap"
author: "Neal Galletti"
date: "9/9/2021"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

Buckle up Kiddos here is how to read this thing! I recapped the entire first round. I put what I thought you were thinking  before you made the pick and then my **reaction is in bold**. That should be simple enough for you pole lickers out there. After that I just went through everyone’s team position by position just giving my overall opinion without really saying anything at all.  Welcome to the new year!(can we get some Motion City Soundtrack playing like it's my myspace page?)

## First Round

1. Christain McCaffery- Running backs win leagues so I will take the best one. **Coward. Mahomes over all.**
2. Patrick Mahomes- I can’t int this pick. I can’t let Joe have Mahomes. But should I take Dalvin? I really want dalvin and qbs are for baddies. I’m not a baddie am I? But Mahomes is “so good”. Tilted. **Proud of you for being toxic enough to yourself, so that you didn’t take the guy you wanted.**
3. Alvin Kamara- Kamara has the highest ppr potential, he's the best pass catcher on the team and they finally have a good qb. Can’t believe Nick didn’t give me Mahomes. **Its an easy pick between Mahomes and Kamara right?**
4. Dalvin Cook- He run ball good. **I don’t think the hangover allowed more thought than that.**
5. Derrick Henry- Honestly hes just a beast and his situation should be just as good with Julio. Joe liked him last year and I don’t want to take a qb this early. **You draft by yourself for the first time this year?**
6. Josh Allen- White dude with a cannon that just had an MVP season. **Honestly predictable for you to take the MVP the following fantasy season.**
7. Kyler Murray- People are down on Kyler after last year. He is veristale player. I lived in Arizona. I want a quarterback. **I wrote the first part before you made a nickname. Feels like a zag pick not surprised you made it.**
8. Saquon Barkley- This guy was a top three pick last year. At 8? He’s a steal! **Did you mean to take Chubb? Good luck on the snap count.**
9. Ezekiel Elloit- All in on the Cowboys offense. **Were you scared of Lamar hurting you twice?**
10. Nick Chubb- Might be the best running back in the NFL. I really like the Browns offense they’re going to run it down everyone’s throat again. **Choosing not to speculate why you AND Josh passed on Lamar…**
11. Lamar Jackson- We can start two qbs and the best rushing one is still here? I’m not a piece of shit like Josh and Boots. **Bonus points for taking Aaron Jones before Tony.**
12. Fuck you all I am the greatest.

Well I got bored of hearing myself type after the first round but let's take a look at everyone’s team. Just scrolling through the draft board I really only looked at your projected starters. Everyone always likes the guys on their bench more than everyone else in the league. I’ll try to keep it formatted but the thoughts probably won’t make sense.

## Lizandro
**QB:**
    So I am going to do everyone a favor and act like you didn’t auto pick Cam with the last pick. I wish I could ignore the rest of your quarterbacks too. Pretty rough start when you have the biggest reach in the draft with Joe Burrow and then two guys that can’t throw the ball past the first down marker. Quarterbacks that win games usually have good fantasy seasons and your three quarterbacks look like they might win 10 games between the three of them.
**RB:**
Yikes. I hope you had a good time making that one pick cause that might the only thing right you did this draft. Welp at least you have CMC not like he’s ever missed a large portion of the season for any reason. But at least you’re ambulance chasing with the rest of your running backs so you’re one fuck up away from having two running backs to start. 
**WR:** 
Chris Godwin! There’s a player I kind of like. Glad I found one. But I am a bucs fan, Got some rookies you can be hopeful for but ya know at least you had fun in Nashville.
**TE:** 
WELP! The country music must have just been calling you to pick dem country boys Kittle and Andrews, Good for you man way to not see race. 
**Summary:**
I hope you have fun in this league. You’re looking good today. I think Joe took the Tacos out of his graph for you because he was worried about being racist. At least you put yourself in a good spot to get your first one this year.

## Nick
**QB:**
Mahomes Mahomes Mahomes Mahomes. Thank you for not passing on him. I know you’re against two QBs, it doesn’t mean you have to draft a corpse to start in your superflex. Maybe you’ve got the biggest of brains and all you need is two guys and a dream.
**RB:**
So this is what you did with all those roster spots instead of getting another person of use, You used 7 draft spots for 4.5 running backs??? Come on man I know you didn't have Matthew Berry announcing your picks but I bet you really liked those WOOOWSSS!
**WR:** 
JUDAS! How dare you take the only true WR handcuff! Why do you have so many players on dead teams? Dolphins, Jets, and the TEXANS???? Man I know you’re toxic but this just seems like self destructive behavior.
**TE:** 
I guess you did good? Josh and Joe wouldn't shout their mouths about either of your guys. I am guessing you didn’t hear about them yourself.
**Summary:**
So instead of making fun of you for taking the wrong guy at 2, I get to make fun of you for fucking up the rest of your picks. Are you going to be the first one to join Tony with the taco two pack this year? 

## Joe
**LEAGUE CHAMP GUEST WRITER**
Why is Kamara –     More like what is this team? Week one and this mother fucker is walking out weak ass Jimmy G and old ass Fitzmagic. I guess all the insider information he has didn’t inform him this is a two QB league. I think no one is a bigger Carolina fan than Joey, but hey maybe this is the year that DJ Moore will win you a championship. Let’s be honest Joe fudges the numbers for his “sims” to make his team always look better than it is. Just remember no one here checks his data and Joe is pretty much a day walker who cannot be trusted. Just bend over and I will be gentle for week one – Love your Daddy.

I clearly did not tell Josh what format I was doing but he didn’t ask either. Honestly glad he took the fuck you approach and may adapt it more going forward. But I will give my summary for Joe anyway.

**Summary:** 
It's good to see you took some more swings than usual this year. Can’t wait to see you tilt when you have guys on the bench going off and you take some L’s. 

## Ty
**QB:**
I fucking hate that you got Rodgers. It is just going to make you softer when Rodgers pegs the bears and you just justify it because you win the fantasy week. 
**RB:**
Holy shit did you make all your picks just to make the Bears schedule hurt the least? Justifying the qbs and running backs for 6 of their 17 games, Incredible.
**WR:** 
I don’t care about the bears non division schedule but finally some guys that are actually exciting and not just a hedge bet on your emo boy feelings. 
**TE:** 
I was big on Higbee about 2 weeks ago. Other than that I don’t really have an opinion. 
**Summary:**
 Well you’ve pretty successfully hedged your football season. Either the Bears play good and you have a bad fantasy season or the Bears lose in shootouts and you have a bad fantasy season. I guess we know your fate either way.

## Jon
**QB:** 
Man you fucking love Russell Motherfucking Wilson. It’s like clockwork. But otherwise at least you have some warm bodies that throw a football otherwise.
**RB:** 
Hey Jon. You only took Derrick Henry. You know you have to start two running backs right? You really did draft by yourself this year.
**WR:**
Love the stack. You just picked some beast of football players and I don’t hate it. Not sure why you drafted two retired receivers but if they come back nothing like throwing to someone using a walker on the field.
**TE:**
All in on the rookie! GL
**Summary:**
 Man Team Diapers, You like em young you like em old either way you’re full of shit. 

## Scott
**QB:** 
Good to see you know your type. White dude’s with big arms. Love seeing the Sam Darnold pick just to cuck the teams that didn’t take enough QBs yet.
**RB:** 
This might be the earliest you’ve taken running backs in this league. Got two guys that expect to stay the field for 3 downs though!
**WR:**
Like the white man stack in LA.  Pretty jealous you got Robby Anderson(Sur Pur).
**TE:** 
Man fuck your tight ends. Davonte isn’t giving up any targets and neither is Jonnu. 
**Summary:**
Welp. You switched up your strategy after getting second last year. Are you going to keep up that win percentage or are you due for a down year? Lots of pressure going into year four. 

## Ryan
**QB:**
Welp. Not only did I know you liked Kyler cause you lived in Arizona but you also found the most useless feature on Sleeper to let everyone know you think he is really good. You better hope he is because he is basically your only QB. Probably a good call to draft Eason but did you really need to spend two picks on Indy’s QB?
**RB:** 
Always knew you were a JT fan but I am not sure why you’re all in on a bad Colts team. You probably haven’t heard but Monte is losing his job this year. Maybe Chase will be on the case!(Paw Patrol Reference for you uncultured swines.)
**WR:** 
Again with the Colts offense. I don’t care if its your last pick. Counting on some high upside young guys all around this year but your receivers are probably your best starting spot so far.
**TE:** 
I don’t care about your TEs.
**Summary:**
I think you have a better chance to make your second playoffs than Lizandro. I just can’t believe you took Carson Wentz still.

## Eric
**QB:** 
Hope Trey Lance starts for you and fucks over Joe. The Red Rocket might only get to start the first half of game one but man you’ll get his 2.5 points that he earns! Taysom Hill might not even get to catch a pass this year.
**RB:**
Big risk with Quon but someone has to take a risk on a top end guy! Nothing like having the best player on their team. 
**WR:** 
Lets see if Scary Terry is a Deandre Hopkins or Jordy Nelson for you this year. Outside of him do you have another receiver? I couldn’t find any. Weird.
**TE:** 
Well shit there’s your other receiver. Nice. 
**Summary:**
Weird stuff man. Your team feels a little like Plinko. You lined up where you’re dropping the disk and we’ve just hit the moment you let go to see what you win at the end. I hate to say it but it looks like only one of us can make the playoffs at a time and I like my chances.

## Josh
**QB:** 
Running it Dak. Establishing the Dallas offense is going to be the new name of your podcast. Some QBs on some new teams to try out. I see Joe has you drinking the Jets hype.
**RB:**
Establish the Rum they said. Josh I think they just picked that as the title doesn’t mean you had to take Zeke first. Can’t believe you didn’t take JT, after hyping him up at 7.
**WR:** 
How are you going to separate your Antonio Browns?? I would be worried about that. Got a couple guys that you’re going to be proud you drafted even if it doesn’t matter for like 5 years. 
**TE:** 
Young exciting guys here. Good luck.
**Summary:**
 I don’t care that you won last year. I hope part of the reason you have 2 Lions in your starting lineup, is because you hedge your game day feelings against the Bears. Guess we will find out if you work in three year sprints or you’ve actually gotten good.

## Tony
**QB:** 
Love the two guys you got. No notes. LET’S GO TOMPA BAY!...well except you should’ve taken a third guy cause its sus you don’t have one.
**RB:** 
I expected to hate your team by this point but the top of your draft is better than expected.
**WR:** 
Man never trusting Juju again.Kenny Golladay is really going to have to become Megatron to be worth anythingggg and I don’t see any other receivers on your team.yikes.
**TE:** 
Jealous of the Ertz pick. I hope he gets traded to the packers for you.
**Summary:**
 I expected to hate your team cause you’re the only one with two tacos, but I’d say this is as good of a year as any to make the playoffs for once.

## Terry
**QB:**
You took QBs I was looking at for your top two guys so I will let you decide if that’s a good thing or a bad thing but either way it makes me upset. 
**RB:** 
Well shit… I gave nick so much shit for wasting so many picks on running back then you just have to go and one up him. What the fuck Terry? 7 Picks and you only got 3 running backs back. You got ripped off and no one even had to do anything to you. I am glad you got to take Aaron Jones from Tony though.
**WR:** 
Decent stacks but man you love Jacksonville thats fucking awesome. I’m happy you pay 25 dollars a year to show us how big of a Jags fan you are truly impressed.
**TE:**
**Summary:**
 Well Terry you got a lot of your eggs in the same baskets and I can appreciate that. Glad to see someone support their team instead of hedging their feelings with their fantasy team. All of you Bears fans are cowards. 

Welp I managed to get this together by the kick off of the season. Just wanted to take this time to thank you all for reading my scattered ideas that I jotted down inconsistently, I’d like to thank Josh for guest writing for Joe’s team. I also wanted to do a couple shout outs: to my mom Hi, to Terry and Tony I am honestly shocked you guys read this but just wanted to say hi as well, to Joe, Scott, Jon, Josh, Ty,  and Eric amazing how lucky you guys have gotten over 6(ish) years, to Lizandro you look good today, to Ryan but for real how excited are you for Kyler?, to Nick I just hope you’re feeling okay man I know the start of the school year was tough on you but I didn’t think things were this bad. I have a phone number if you ever need help 1800-438-4663. Alright everyone this has been my thoughts. I did not proofread anything before sending it to Joe to post. I just hit send and let it fly at the bottom of the page! Good luck everybody else!
