---
title: "Week 6 Recap"
author: "Scott"
date: "10/19/2021"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---
## 1.	Joe (Why is Kamara?) 1-5
### PF: 693.5 PA: 871.96 True Rank: 12
Just through the 1/3rd mark of the season, you have to start asking where did it all go wrong? Finishing last season in 4th place, Joe finds himself in the back of the pack after week 6. The FF Data Expert’s fall from grace hasn’t been pretty but if Fitz was around would it be any different? A QB room that is barren but still has our King - Justin Fields - whose development depends on that piece of shit Matt Nagy, and can only get you so far right now with the pressure he is facing up front but I do like him as a serviceable guy for the rest of the season. Jimmy G can’t stay on the field and possibly stinks but I think you are saved by Trey Lance definitely not being ready yet, maybe you will have a chance to get Fitz back in a few weeks? The let down has been the Waller-us, I was all in on him but besides week 1 he really has not performed to his value and in some cases, been ass. You’re stuck in limbo with Waller because he is a permanent start and you just hope he can bounce back to a higher target share. The RBs are Alvin Kamara and bunch of schmucks you hope can break 10 points each week with whoever you choose from the carousel, the upside is the Saints offense has been looking more fluid so maybe Kamara can maintain a 30pt clip each week. As for receivers, Stefon Diggs and DJ Moore have been solid as a WR combo most weeks but Lockett/Shenault have been inconsistent and Tyler Lockett is going to be fucked in that trashfire that is the Seahawks without Russ. Low on FAAB, low on hope, it’s going to be a long and dark rest of the season.

## 2. Liz (Jonesing for a Godwin) 2-4
### PF: 798.42 PA: 811.58 True Rank: 9
Let’s start with the positive… at least your true rank is higher than your league standings, so you’ve got that going for you. But other than that, not much has gone your way. One upside I guess you can claim the 2 Premiere TE’s paid off because without Mark Andrews to save George Kittle from himself you might be with Joe at 1-5. Another positive thing you can look at is the workload and productivity of Henderson, hopefully he can at least stay on the field unlike Mccaffrey. Just like George Kittle, your QB situation continues to try and get themselves killed. What is Joe Burrow trying to prove taking on multiple linebackers for short yard scramble, its idiotic. Maybe with $100 you can make a splash play but I can’t say the season outlook is positive.

## 3. Anthony (AnthonyClay) 2-4
### PF: 799.3 PA: 857.12 True Rank: 8
I am currently unsure if you will be able to field a full team next week because 50% of your roster is currently on IR or out. Maybe it’s bad luck, maybe it is karma for drafting the *alleged* all time league leader in sexual assaults. Either way I love Herbert and think Tom will perform for you week in week out but QBs can only carry you so far. If you can get Michael Thomas and/or Jarvis back in a couple weeks you’ll have a chance. Other than that I think your team is going to continue to struggle and if the injuries don’t improve or continue you may find yourself below Liz…. possibly below even Joe.

## 4. Neal (3-2) 2-4
### PF: 821.52 PA: 781.78 True Rank: 7
Neal, Neal, Neal. Love a preemptive W. The good news is you’re the first 2-4 team that I think has a chance to perform better through the rest of the season butttt also could be much worse. Our king Jameis is only going to become more comfortable in the Saints offense and is definitely ONLY going to throw bombs to his guys and will NOT throw ridiculous interceptions to the linebackers while being sacked (the lasik is kicking in). The real question marks come at your other QBs, I want to believe in Tua-time and Hurts but both of their offenses just look so bad and I don’t even think it is a product of them but their surroundings. I’m not even going to acknowledge the other quarterback you have because he is a fuckin bum. On the plus side, your draft strategy of taking 4 straight receivers paid off because Allen Robinson fucking blows and at least you can fill that void. While we all anticipated your RB room to struggle, I don’t think anyone expected it to be this bad this year. 5 points this week from the RB position??? What are we doing here? Anyways you finished 7-6 last season and you’re going to have to climb out of a hole here to hope you can get to .500 on the season.

## 5. Nick (Mahomies Like ESPN More) 2-4
### PF: 839.78 PA: 918.7 True Rank: 6
Let’s get the obvious out of the way, you have been hosed on matchups. Your record of 2-4 should be better based on you having the highest PA by a solid margin and not a terrible PF relative to the bottom third of the league. I’m guessing you caught Ryge on a week where his team went nuclear. Your QB room is horrifying, while I like Tik-Tok Star Jackson Mahomes’ brother as your QB1, I can’t stand seeing QB2 as old fat Ben dropping back and checking down on a swing pass on 4th and 7. It’s a coin flip between ben and geno. Wide Receiver room is looking solid, besides Kupp stealing all the work from Robert Woods and Mike Evans having to share between 20 targets your room is solid. Brandin Cooks somehow is Mr. Consistent no matter who is the QB, maybe it’s because he’s the only viable target on the team. You having 85 running backs on your roster but only 2 see enough opportunities to even be serviceable. Somehow you’ve handcuffed the worst Running back field in the league with the dolphins which might be signs of a psychopath but I’m still doing my research on that. 

## 6. Ty (Cookin’ up Some Losses) 3-3
### PF: 700.02 PA: 833.3 True Rank: 11
I hate to be the bearer of bad news but Ty, your team has caused my fraud-o-meter to go off the charts and says that your team as true rank 11 is going to struggle to win going forward unless some changes are made. 700 PF is only 7 more than the lowest in the league and your PA is right around middle of the league, yet you have scraped by to survive at 3-3 and be 6th in standings so maybe my meter is broken, time will tell. I love that you Have Arodge but he will only be able to take your team so far on his own. Other than that you have  an underperforming WR room and a RB where only one see’s the field all the time (I guess sanders does but Siriani doesn’t run or pass to him enough even though he is their best veteran offensive player) and Hunt just went to the IR. Tyler Higbee went 5/5 and that was the receptions (5) and second most targets (5) on your entire team, that is terrifying. Ponder that statistic for a bit,  maybe you can find a solution.

## 7. Josh (Running it Dak) 3-3
### PF: 848.14 PA: 868.96 True Rank: 5
Last seasons champ, your team is sitting at the top of the middle of the pack with true rank 5. I mostly hate your team because you have 2 A. Brown as it is listed on the Sleeper rosters and that pisses me off to look at plus one of them is a pretty horrible person so it reaffirms my position. I wish I could say your team is a fraud because there is nothing flashy about it but god dammit I can’t. It might be the model of consistency (possibly mediocrity?) of our league because nobody is going to drop a donut on you but there really isn’t the 35+ pt ceiling/explosion guys either. Zeke is back to being himself when it comes to his modern workload, with Pollards productivity I don’t think he will ever go back to the Derrick Henry type workload. Hockenson/Swift is the most upside for your team in my opinion, they are the 2 primary targets on a Lions offense that *hopefully* can’t get worse than it is, I can’t stand to see Man Campbell cry again. Hopefully your starters stay healthy because you have no apparent depth on your roster and nobody wants to have to rely on Zach Wilson to not get negative points.

## 8. Terry (Thielen up my Cousins) 3-3
### PF: 936.14 PA: 888.94 True Rank: 3
After crunching the data Terry and his CoCo Cousins have come out at True Rank 3. With an impressive 3rd most PF and 2nd highest PA, Terry’s team has underachieved so far but looks to be just fine in the long run as long as he sticks to what he is doing. If Marquise Brown caught 1 of the 3 bomb touchdowns from Lamar a couple weeks ago maybe these standings look a little different. At first glance your team is quite deadly. Lamar is unstoppable, Kirk Cousins is the definition of a trash player that puts up great numbers, this team just has it all! In all seriousness your QB room puts up great numbers in Lamar and solid numbers each week with Kirk and Lawrence. With both Lawrence and James Robinson I think the game scripts of playing from behind and TLaw looking for check downs will continue throughout the season and also help develop a chemistry (someone tell Urban to keep Carlos Hyde bitch ass off the field). Aaron Jones and Joe Mixon have looked great so far and as long as they’re healthy they aren’t going to lose any opportunities. I don’t want to curse it Terry but it looks like you have a strong chance at a playoff run, besides injuries the only thing holding you back is a covid outbreak which has already started with Goedert and Perine… who’s next?!

## 9. Eric (Full Chuba) 4-2
### PF: 777.68 PA: 814.36 True Rank: 10
It hurts to do this but Full Chubba is the second team in the standings that has caused my Fraud-o-meter to bust. The 3rd lowest PF and the 4th lowest PA, a True Rank of 10 has some people are asking… how are you 4-2? What black magic is keeping your team alive each week? Your QB room… can we even call it that when 2 of your QBs are mostly rushing? Baker is going to do Baker things like be average and get hurt (but not injured) each game. And I think you may be in trouble with Trey Lance clearly not being ready yet and if Jimmy G is good to go I think Shanahan will stick with gadget plays for Lance while developing him. You have 2 solid WRs and sterling Sheppard, the problem there is all their offenses are an atrocity to man so their ceilings are very limited. Without Saquon (hope for the best) you have a RB room of secondary backs and handcuffs which sometimes pays off and in your case it definitely did. Collins and Hubbard are nothing to write home about but at least they’re seeing the field and can at least give you a floor week to week. Conner and Moss are….. whatever, theyre serviceable as flexs given your injury situation. 

## 10. Jon (CeeDeezNutz [HA!]) 4-2
### PF: 869.56 PA: 759.34 True Rank: 4
Derrick “Tractor-City” Henry not only carries the Titans, he carries your team. He was a top pick before anyone even CONSIDERED the possibility that he would be added to the passing game, even a few targets here and there can be huge for a bell cow back when it was always anticipated to be 0. The elephant in the room the is being covered by the larger elephant Derrick Henry is Russ is going to miss a significant amount of team and your team has not felt the consequence of that just yet, will you be able to survive with Matty Ice and without Derek Carr week 8? We will have to see, but your QB situation still is better than probably 40% of the league at this point of the season. Your RBs besides Henry are tough to look at for the most part and especially hate looking at fucking Cordarrelle who you stole from my cold dead hands just as the clock hit 12:05pm and waivers went through. Your WRs are pretty much solid all around getting a lot of opportunities. Odell has to figure it out with baker eventually, right? Right??? It doesn’t make sense dammit! True Rank 4 no fault of your own but the low PA and with Terry’s higher PF and PA it allowed you to slip a rank. I plan on meeting in the playoffs once again.

## 11. Scott (Inglorious Staffords) 4-2
### PF: 976.04 PA: 838.56 True Rank: 2
As Neal stated in the draft recap “You like white guys with huge arms” and god dammit if it hasn’t held true. From back to back Mahomes years (and one with Maserati Mitch there babeh) to this year, I think it has mostly paid off. The real steal of the draft for me I think was the handcuff of Cooper Kupp with Matt Stafford because if Stafford has a fantastic game, Kupp is getting a large percentage of those opportunities. Have you heard they’re breakfast buddies? Im sure a broadcast may have mentioned it before (/s). My other WRs are fucking bums, did Robbie Anderson die? I tried to ride it out but the dude just can’t catch a ball. Michael Pittman is whatever but Carson Wentz is screwing me with the high variance of targets for Pittman week to week. This is definitely my best season of Running Backs in this league by a country mile, Najee Harris I lucked out with because the steelers have a horrendous offense and ben stinks so he is basically forced opportunities even if he average 2 yards. And who let me get 3 mediocre TEs and to roster all of them? What am I doing here? This is fucking ridiculous. Anyways, I’ve got my sights set on the playoffs and i’ll see you guys there. 

## 12. Ryge (Kyler, The Creator) 6-0
### PF: 1013.96 PA: 829.46 True Rank: 1
What’s there to say? The Only team to hit 1000+ PF after week 6 IN SPITE of having Carson Wentz as one of your starting Quarterbacks (disgusting). It really makes me think about what if I didn’t take Sam Darnold 1 pick before you and you had him in your arsenal too? Scary to think about really. Kyler is going nuclear and as long as he stays healthy he is going to rack points for you. Your two picks where their value is now way above their ADP are definitely Playoff Lenny in the 9th round and Jamaar Chase in 6th round, that fact that Jamaar Chase trolled the world with “I can’t see this ball that well” and he fell 3 rounds should be a war crime. Your team has a lot of depth all over the place so even more injuries come your way you should be able to survive and advance. As of now I don’t really see a way your team slips from the top 4, only Carson Wentz reverting to last year could slip you up.

## True Rankings:
1. Ryge
2. Scott
3. Terry
4. Jon
5. Josh
6. Nick
7. Neal
8. Anthony
9. Liz
10. Eric
11. Ty
12. Joe
