---
title: "Week 4 Preview"
author: 
  - name: "Josh Noel"
date: "09/28/2023"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

## Geno 911 vs Dak to December

The battle of the 2-1's should be a fun match up if my players don't start dropping more 40 bombs. Hey at least Liz can't mess up which Seahawks back to play this week. Liz's team looks dangerous but mostly has been underperforming this year. If my team does not go nuclear this week, we can pretend it may be a close one.

**Winner -- Geno 911 -14 (for those gambling addicts)**

## Team Neal vs Bryce is Right

The Galletti bowl is looking a little one sided this week. It's not like Ryge's team is that good but more like Neal's running backs are that bad. Neal, if you don't play your first round pick you're kind of a wuss. I will even let you change his position to RB like the Bears should. Terrelle Pryor had a 1000 yard receiving season after all. This has the looks of the Dolphins vs Broncos of fantasy football this week.

**Winner -- Bryce is Right -20**

## See You in Kell vs Bateman and The Ridder

How the fuck is this our undefeated match up???? Scott is starting 2 TEs and Joe unironically tried to start the year with a Ridder and Drake London stack. Joe may narrowly win another game with A-Rich coming back, Ekeler possibly playing, and hoping some more Achane magic shows up. To be honest Joe starting two Pats players makes my soul happy and Scott running 1.5 RBs instead of no RB is close enough to keep the tradition alive.

**Winner -- Bateman and The Ridder -3**

## A Smith in the Hand vs Dan Flash's Speedsters

Ty somehow has Puka and Cheetah but is 0-3. I know it seems crazy until you see what he runs out week after week at QB. Ty's love for Danny Dimes will never cease to amaze me. He's more committed to Danny Dimes than the team that guaranteed him \$82 million. Jon's team seems solid especially if some of his receivers can get rolling and apparently Saquan decided to superman his injury to play this week. For some reason sleeper has this match up at 50/50 but looking at it seems like Jon's team is in a better spot.

**Winner - A Smith in the Hand -7**

## Just Joshin' Around vs Ceed Deez Nuts on ESPN

Eric has by far the best name and picture in the league. The sex appeal of his team is unmatched and you know he is kind of a bad boy for picking Ridley. Both teams have some sneaky good picks in James Conner and Tank Dell. So, Mr. Big Ass Duncan, Calvin Ridley is an acceptable bad boy because he did a little gambling. Deshaun is a scummy human who isn't supposed to be on a roster. "I'm the Joker of the League" but really you're just kind of a clown.

**Winner -- Just Joshin' Around -5**

## Easy Pickens w/ Ma-Homies vs Chubb One Out

Colt I don't know if you are going to read this, but your team is kind of a dumpster fire bud. I will acknowledge that injuries ruined any chance you had at being not terrible. Nick G is going to be enjoying the bye this week with the scariest QB duo in the league. Kyren Davis may be the best pick in the league by the end of the season, but depth may be what gets you later in the season.

**Winner - Easy Pickens W/ Ma-Homies -25**
