---
title: "Week 3 Recap"
author: "Ryan Galletti"
date: "9/28/2021"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---
## 1.	Joe
The expert, Joe. In case you didn’t know Joe studies FF year round and crunches the numbers each year. Some how he always finds his way deep into the post season. This year however he finds himself in last place early on in the year. A team that relies on Justin Fields and Jimmy G at the most important position will not go far. A starting backfield of Alvin and Williams doesn’t look to great for a guy who loves to carry RBs. Just wait to Alvin goes down I have his handcuff waiting to take over. Diggs, Moore and Locket might be the strength of the team. Which is unusual for a Joe team. As for the bench not a whole lot going on there either. Makes me wonder did Joe not do his homework this year or did he give terrible advice to the 3 people that use his website?

## 2.	Neal
Who is shocked Neal tried to take a monopoly on the WRs again. So far not so good. Top 4 picks were WR and not one is a Top 4 guy at the position so far. One is on the Bears, and we know how that is going. Another isn’t even the top WR on his team, I have the new 1 for the bolts. If I remember correctly Neal offered up his QBs like they were actually of interest to anyone other than Joe. Nobody in the league wants any of your QBs. As I finish looking at your team is there even a RB1 on your roster?

## 3.	Tony
A man who shares a love of the packers so I can’t be too mean. I will start by saying you have a very nice QB room even if you do have a man who is accused by many women. If Herbert or Brady go down you better spend that FAAB if not your season may be over. It’s a major risk and if I were you I’d stash their backups. Hint hint Watson and Bell won’t see the field this year… When I look at your RB back room I think of Joe’s team in the past. A few solid guys but just have to hope Hunt doesn’t take anymore time away from Chubb. You have the handcuff in Vegas so no need to worry about Jacob’s. Looking at the WRs I am not sure how Kirk isn’t starting every week for you. You do know he plays with Kyler?

## 4.	Jon
The little Bro to the master. Another Syd that normally finds his way into the post season. This year doesn’t look so great for you. A team with one RB, Henry, maybe that’s all you need when it is in fact him. You and Russ should be a married couple by now because you do not let anyone touch or even look at Russ ever. Lamb and Metcalf look really good but so far they haven’t been as great as you would have hoped. Maybe they will bounce back. Pitts and Cook at TE isn’t bad but Cook is old and Pitts is a rookie TE on a not so great ATL team. As I leave your team I’m not sure what the plan is if Henry goes down. Maybe a trade will be coming? 

## 5.	Liz
A team I can normally count out to be as bad as mine normally is. This year is no different other than my team looks much better than normal. I’m glad you reached for Burrow because I really wanted him this year and you saved me from that.  Burrow Jones and Goff isn’t great but hey at least you have 3 starting QBs. That better than some in the league. CMC is so hard to pass up but going forward people may have to consider passing on him with this injury history. You need Henderson to come back quick and also hope he returns to the week 1 and 2 of himself. If not you might not see any production from the RB position. Godwin is a solid guy at WR but after that so you have anyone other than a washed Julio? Looking at your bench I see Cam still chilling. I know it was on Auto at the time but you now have control of your team you can drop him. Before I go I had to ask did you Josh whisper some sweet nothings into your ear about how two “premier” TEs are actually a good idea? 

## 6.	Nick
Two time manager of the week!! First I want to say sorry that Liz upset you this week and took your crown. Sometimes you have to give up your crown to actually win games in this league. So many things to pick apart about this team. Let’s starts at QB. Mahomes is good but is Ben? If one goes down what’s the plan? Now let’s look at RB. Two running backs only and both are on bad teams. Not sure how that’s going to work for you. At least you have the handcuff on that unstoppable Miami run offense. Now let’s look at your best? position WR. Hopkins Evans Cooks and Woods looks really good on paper. Maybe they can come together and carry your team but we will have to wait and see. My only question as I leave your team is how many times have you tilted already knowing you have 0 depth? 

## 7.	Terry
First if all good game this week. I was worried watching Kyler only put up 18 points. Probably the best looking RB room in the league I don’t have much to say about that. When it comes to QB you have two guys who are play pretty well. If something happens to one or Kirk starts to suck you don’t have have anyone to turn too. Lawrence has been bad but it gets to slide because it’s Urban with a number 1 pick. After Thielen not much going on at WR. Hollywood is about to go down hill since he forgot to catch a football. The major downside to your team is no depth beyond the starters. Who has a better plan in place you or Nick when something goes wrong? 

## 8.	Ty, big brother Noel
I’m going to be honest I have no clue how this team won 2 games. A positive you have going is that Aaron is starting to look the MVP again. After him your QB position really takes a hit. Billy boy should have kept Cam. Mac just isn’t cutting it. Dalvin Cook isn’t being Dalvin Cook. Maybe when he is healthy he can bounce back. If not you better hope Hunt can push for major playing time In Cleveland. I was going to talk about your WRs but I didn’t see a WR1 or even a WR2 on this roster. Again how did this team win 2 games? 

## 9.	Eric
Another team that has 2 wins but I’m not sure how they got their either. Eric you do realize you only have 1 starting QB on your team? His not even a QB2 in most leagues. One thing you have going is that the Bears are even worse when starting Fields. Nagy is smart enough to realize his on the hot seat but is he stubborn enough to put Dalton back in? Barkley and Carson are a solid RB duo. Barkley hasn’t gotten out too hot but had a nice week 3. If he keeps this up your team might be in okay shape. CMC going down might truly give your team a boost and Cubba was a great pickup for that reason. Debo is a nice WR but after that who else do you have? Before leaving I have to wonder did you Josh and Liz all share a moment with your sweet nothings about “premier” TEs? 

## 10.	Josh
A closet Green Bay fan. Always has to have one on his team. Allan is the lucky guy this year I see. This is the first team I can see being 2-1. Dak and Teddy may not be putting up huge numbers but they are certainly doing enough to get the job done for you. I’m sure it feels good to hold Joe’s favorite player too with Wilson. Zeke and Swift are holding down the RB position well for you. I just wonder when Swift cools off. After all he is a Lion. AJ is supposed to be your big WR but he hasn’t done anything this year. To add insult to injury he might be out for some time. After him you don’t have anything at WR. I was leaving I wondered how did you trick Eric and Liz into taking two “premier” TEs? 

## 11.	Scott
Maybe the most scary team in the league. Josh Matt and Sam is a great QB trio. I still didn’t forget about how you stole him from me. Eckler and another stolen pick from me Harris are putting up Greta numbers. Here’s where things start to go down hill. After Kupp do you have anyone who receives the ball in the NFL? If Harris or Eckler were to stumble where do you go? As with a few of our friends at the bottom of the standing there is no depth here. If someone goes down is there a backup plan in place to stay at the top? 

## 12.	Me
Everyone’s favorite Galletti. A team built around The Creator, Kyler. After Kyler we have Mills and Wentz. Not great but that’s 3 starting QBs and that’s what you need in this league. As for RBs we have 4 starting RBs. You heard that right folks 4 starting backs. All 4 can start at anytime. At the WR position we have 4 guys who are WR1 at worst WR2 guys. That Geuax Tiger connection in Ohio is really working. I’d also be lying if I told you who Mike Williams was before this year. Nonetheless he’s turning out to be the pick of the year so far. Yes I carry 3 TEs currently but that’s because I know I have to play the matchups with them. When guys come off the IR one of them may become available in FA. Speaking of IR. I have another possible WR1 coming back. Another starting caliber RB. And another starting QB. This team looks good and whether you want to admit it or not my team is good and one to be reckoned with this year. See you all in week 4. 

For those wondering why the numbers are backwards it to make those at the bottom of the standing feel better. Or is it? 